In [17]:
#Task 2
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
import pandas as pd
import matplotlib.pyplot as plt
#Đọc file csv
df = pd.read_csv('/Users/lengochuynh/Documents/Zalo Received Files/Practice 03/Task 1/Practice03_group3.csv')
df

Stt  Height(cm)  Length_of_hair(cm)  Voice_pitch  Class
0    1         180                  15            0    Man
1    2         177                  42            0  Woman
2    3         136                  35            1  Woman
3    4         174                   6            0    Man
4    5         141                  28            1  Woman
5    6         180                  20            0    Man
6    7         158                  29            1  Woman
7    8         150                  20            1  Woman
8    9         175                   4            0    Man
9   10         180                   7            0    Man

In [18]:
#Task 3
# X
import pandas as pd
import numpy as np

# Đọc dữ liệu từ file CSV vào DataFrame
csv_file_path = ('/Users/lengochuynh/Documents/Zalo Received Files/Practice 03/Task 1/Practice03_group3.csv')
df = pd.read_csv(csv_file_path)
df = df.iloc[:, 1:-1]
# Chuyển đổi DataFrame thành ma trận NumPy
matrix = df.values
# Hiển thị ma trận
print(matrix)

[[180  15   0]
 [177  42   0]
 [136  35   1]
 [174   6   0]
 [141  28   1]
 [180  20   0]
 [158  29   1]
 [150  20   1]
 [175   4   0]
 [180   7   0]]


In [19]:
# Y
csv_file_path = ('/Users/lengochuynh/Documents/Zalo Received Files/Practice 03/Task 1/Practice03_group3.csv')
df = pd.read_csv(csv_file_path)
last_column_data = df.iloc[:, -1].tolist()
print(last_column_data)

['Man', 'Woman', 'Woman', 'Man', 'Woman', 'Man', 'Woman', 'Woman', 'Man', 'Man']


In [20]:
# Task 4
# Chia dữ liệu thành tập huấn luyện và tập kiểm tra
X_train, X_test, y_train, y_test = train_test_split(matrix, last_column_data , test_size= 1/3, random_state=42)

# Khởi tạo mô hình Decision Tree
group3 = DecisionTreeClassifier()

# Huấn luyện mô hình trên tập huấn luyện
group3.fit(X_train, y_train)

# Dự đoán trên tập kiểm tra
y_pred = group3.predict(X_test)
print(y_pred)

['Man' 'Man' 'Man' 'Man']


In [22]:
# Task 5
# Nhập 3 bộ phân loại giới tính
X = [
    [153, 32, 0],
    [163, 14, 1],
    [173, 10, 1]
]
# Chuyển dữ liệu thành mảng 2D

new_data_array = np.array(X).reshape(len(X), -1)

# Dự đoán giới tính cho dữ liệu mới bằng mô hình đã huấn luyện
predicted_gender = group3.predict(new_data_array)

# In kết quả dự đoán
for i, prediction in enumerate(predicted_gender):
    print(f"Bộ {i+1}: Predicted Gender: {'Nam' if prediction == 0 else 'Nữ'}")

Bộ 1: Predicted Gender: Nữ
Bộ 2: Predicted Gender: Nữ
Bộ 3: Predicted Gender: Nữ
